version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
      - ./buckup:/usr/share/elasticsearch/backup
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - path.repo=/usr/share/elasticsearch/backup
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
       - 5601:5601
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
